### ISSUE TITLE
functions for saveAndIndex & addRecord; jsdb.use is not a function

### ISSUE THREAD

**Issue by tony-shannon** [robtweed/qewd-jsdb#1]
in this section of the tutorial
https://github.com/robtweed/qewd-jsdb/blob/master/REPL.md#implementing-apis-to-maintain-data-and-index-records

the saveAndIndex and addRecord functions look ok
all actions on telDirectory beforehand have worked fine
until go to addRecord with this line
addRecord(record, jsdb)

for some reason I am getting this error when trying to invoke these functions?
jsdb.use is not a function
at saveAndIndex (repl:4:27)
at addRecord (repl:9:9)
ie back to this line
var telDoc = jsdb.use('telDirectory');

![image](https://user-images.githubusercontent.com/939996/74605377-87783880-50bf-11ea-93ea-4f163079487d.png)

Either - my mistake or bug/documentation issue?
Ideas welcome ,thanks

**Comment by tony-shannon** [comment]
I think I see an issue in the function syntax..

the addRecord function 
assigns telDoc = jsdb.use('telDirectory)
then
invokes saveAndIndex(id,recordObj,telDoc)

so it passes telDoc as the third parameter to the saveAndIndex function, which is the jsdb parameter ie function saveAndIndex(id, recordObj, jsdb) {...

and within that saveAndIndex function telDoc is again set up as a variable from the jsdb parameter input
 var telDoc = jsdb.use('telDirectory');

..so telDoc seems to be invoking itself telDoc ?

**Comment by robtweed** [comment]
In addToRecord, change:
saveAndIndex(id, recordObj, telDoc);
to
saveAndIndex(id, recordObj, jsdb);

I'll fix this typo soon

**Comment by tony-shannon** [comment]
Yes that was it, sorted here thanks...

**Comment by tony-shannon** [comment]
Heres a PR to save a keystroke , perhaps!
https://github.com/robtweed/qewd-jsdb/pull/2
